"""
video_editing/ai/edit_plan_schema.py
Strict Schema Validator for AI Edit Plans generated by Ollama.
Rejects invalid operations, non-existent scene IDs, negative timestamps, and malformed plans.
"""

import json

ALLOWED_OPERATIONS = {
    "insert", "overwrite", "move", "trim", "split", "delete", "place_video", "place_audio",
    "transition", "visual_effect", "align_audio_beat", "move_audio", "trim_audio", "delete_audio"
}

ALLOWED_TRANSITIONS = {"cut", "dissolve", "fade", "crossfade"}
ALLOWED_EFFECTS = {"brightness", "contrast", "opacity", "color_balance", "saturation"}
ALLOWED_TRACK_TYPES = {"video", "audio"}


def validate_edit_plan(plan_dict: dict, media_metadata: dict = None, scene_list: list = None) -> tuple[bool, dict]:
    """
    Validate an AI Edit Plan dict against strict schema rules.
    Returns (is_valid, response_dict).
    If valid: (True, {"success": True, "error": None})
    If invalid: (False, {"success": False, "error": {"code": "INVALID_EDIT_PLAN", "message": "..."}})
    """
    if not isinstance(plan_dict, dict):
        return False, _err("INVALID_FORMAT", "Edit plan must be a JSON object.")

    # Check top-level required keys
    required_keys = ["edit_goal", "target_duration", "aspect_ratio", "style", "scenes", "operations"]
    for k in required_keys:
        if k not in plan_dict:
            return False, _err("MISSING_FIELD", f"Edit plan missing required top-level field '{k}'.")

    # Validate target_duration
    target_dur = plan_dict.get("target_duration")
    if not isinstance(target_dur, (int, float)) or target_dur <= 0:
        return False, _err("INVALID_TARGET_DURATION", f"target_duration must be a positive number, got {target_dur}.")

    # Build known scene ID lookup
    known_scene_ids = set()
    if scene_list:
        for sc in scene_list:
            if isinstance(sc, dict) and "scene_id" in sc:
                known_scene_ids.add(sc["scene_id"])

    # Also register scenes declared inside the plan itself
    plan_scenes = plan_dict.get("scenes", [])
    if not isinstance(plan_scenes, list):
        return False, _err("INVALID_SCENES", "scenes must be a list.")

    for sc in plan_scenes:
        if isinstance(sc, dict) and "source_scene_id" in sc:
            known_scene_ids.add(sc["source_scene_id"])
        elif isinstance(sc, dict) and "scene_id" in sc:
            known_scene_ids.add(sc["scene_id"])

    # Validate operations
    operations = plan_dict.get("operations", [])
    if not isinstance(operations, list) or len(operations) == 0:
        return False, _err("EMPTY_OPERATIONS", "Edit plan must contain at least one operation.")

    source_dur = media_metadata.get("duration", 0.0) if media_metadata else 0.0

    for idx, op in enumerate(operations):
        if not isinstance(op, dict):
            return False, _err("INVALID_OPERATION", f"Operation at index {idx} is not an object.")

        op_type = str(op.get("type", "")).lower()
        if op_type not in ALLOWED_OPERATIONS:
            return False, _err("UNSUPPORTED_OPERATION", f"Operation type '{op_type}' at index {idx} is not supported.")

        # Specific Phase 3 Operation Schema Checks
        if op_type == "transition":
            t_type = str(op.get("transition_type", "cut")).lower()
            if t_type not in ALLOWED_TRANSITIONS:
                return False, _err("UNSUPPORTED_TRANSITION", f"Transition type '{t_type}' at index {idx} is not supported.")
            if "duration" in op and op["duration"] is not None:
                if not isinstance(op["duration"], (int, float)) or op["duration"] < 0:
                    return False, _err("NEGATIVE_TIMESTAMP", f"Transition duration at index {idx} must be non-negative.")

        if op_type == "visual_effect":
            eff_name = str(op.get("effect_name", "")).lower()
            if not eff_name or eff_name not in ALLOWED_EFFECTS:
                return False, _err("UNSUPPORTED_VISUAL_EFFECT", f"Visual effect '{eff_name}' at index {idx} is not supported.")
            if "value" in op and op["value"] is not None and not isinstance(op["value"], (int, float)):
                return False, _err("INVALID_EFFECT_VALUE", f"Visual effect value at index {idx} must be numeric.")

        if op_type == "align_audio_beat":
            if "beat_time" in op and op["beat_time"] is not None:
                bt = op["beat_time"]
                if not isinstance(bt, (int, float)) or bt < 0:
                    return False, _err("NEGATIVE_TIMESTAMP", f"align_audio_beat beat_time at index {idx} must be non-negative.")

        # Check scene reference if provided
        sc_id = op.get("source_scene_id") or op.get("scene_id")
        if sc_id and known_scene_ids and sc_id not in known_scene_ids:
            return False, _err("INVALID_SCENE_ID", f"Operation at index {idx} references non-existent scene '{sc_id}'.")

        # Timestamp validations
        if "in" in op and op["in"] is not None:
            in_val = op["in"]
            if not isinstance(in_val, (int, float)) or in_val < 0:
                return False, _err("NEGATIVE_TIMESTAMP", f"Operation at index {idx} has negative 'in' timestamp: {in_val}.")

        if "out" in op and op["out"] is not None:
            out_val = op["out"]
            if not isinstance(out_val, (int, float)) or out_val < 0:
                return False, _err("NEGATIVE_TIMESTAMP", f"Operation at index {idx} has negative 'out' timestamp: {out_val}.")
            if "in" in op and op["in"] is not None and out_val <= op["in"]:
                return False, _err("INVALID_TIMESTAMP_RANGE", f"Operation at index {idx} has 'out' ({out_val}) <= 'in' ({op['in']}).")
            if source_dur > 0 and out_val > source_dur + 0.1:
                return False, _err("EXCEEDS_SOURCE_DURATION", f"Operation at index {idx} 'out' ({out_val}s) exceeds source duration ({source_dur}s).")

        if "timeline_pos" in op and op["timeline_pos"] is not None:
            pos_val = op["timeline_pos"]
            if not isinstance(pos_val, (int, float)) or pos_val < 0:
                return False, _err("NEGATIVE_TIMESTAMP", f"Operation at index {idx} has negative 'timeline_pos': {pos_val}.")

        if "split_time" in op and op["split_time"] is not None:
            st_val = op["split_time"]
            if not isinstance(st_val, (int, float)) or st_val < 0:
                return False, _err("NEGATIVE_TIMESTAMP", f"Operation at index {idx} has negative 'split_time': {st_val}.")

        if "track_index" in op and op["track_index"] is not None:
            ti_val = op["track_index"]
            if not isinstance(ti_val, int) or ti_val < 0:
                return False, _err("INVALID_TRACK_INDEX", f"Operation at index {idx} track_index must be an integer >= 0, got {ti_val}.")

        if "track_type" in op and op["track_type"] is not None:
            tt_val = str(op["track_type"]).lower()
            if tt_val not in ALLOWED_TRACK_TYPES:
                return False, _err("INVALID_TRACK_TYPE", f"Operation at index {idx} track_type must be 'video' or 'audio', got '{tt_val}'.")

    return True, {"success": True, "error": None}


def _err(code: str, message: str) -> dict:
    return {
        "success": False,
        "error": {
            "code": code,
            "message": message
        }
    }
